Dev branch
orangeatom/rsvpu_schedule_bot pull request #2
Opened 2016-10-29 13:33 UTC by orangeatom

2016-10-29 14:37 UTC, b0g3r requested changes

2016-10-29 14:37 UTC, b0g3r commented on init.py
> +    GR = Group.create_or_get(group_id=groups[group], group_name=group)
обычно используется конструкция вида

``` python
GR, _ = Group.create_or_get(group_id=groups[group], group_name=group)
```

_ - является валидным именем для переменной, но в коде обычно используется исключительно как заглушка

2016-10-29 14:37 UTC, b0g3r commented on init.py
> +groups = parser.update_links()['groups']
Правильно ли я понимаю, что здесь дважды вызывается функция? нужно от этого избавиться. 
Есть вариант с предварительным созданием переменной, типа 

``` python
data = parser.update_links()
groups = data['groups']
teachers = data['lecturers']
```

либо вот такой путь (тоже неплохой)

``` python
groups, teachers = parser.update_links().values()
```

2016-10-29 14:37 UTC, b0g3r commented on parser.py
>  schedule_url_half_day = 'http://www.rsvpu.ru/racpisanie-zanyatij-zaochnoe-otdelenie/'
http://en.wikipedia.org/wiki/Distance_education

2016-10-29 14:37 UTC, b0g3r commented on parser.py
>      dictionary['lecturers'] = get_info(Soup,'fprep')
в коде используется как `lecturers` так и `teachers` - выбрать что-то одно

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +DB = SqliteDatabase('documents/users.db')
с маленькой

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
>  class state:
с большой

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
>  class User(Model):
хранить лучше в отдельном файле `model.py` - туда же вынести инициализацию бд, все модели и всю логику, связанную с моделями внести в модели

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
>      Lecturer_id = CharField(null=True)
все поля - с маленькой

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +class search_type:
С большой

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +    if type != 2:
`SearchType` определил, но используешь всё равно цифры
`type` - зарезервированное слово, замени лучше на search_type

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +            print(teacher.teacher_name)
задание на будущее: разобраться с логгером, все `print` переделать в вызовы `logger`

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +    choice.sort()
?
есть есть необходимость сортировать, то либо делать это в return, либо использовать `.order_by()` в `peewee`

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +def search(str, type = 0):
поиск чего? добавить в название

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +    if type != 2:
Почему `!=`? выглядит не слишком очевидно

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +def format_day(container,day,count):
`container` - неясно что это
функция делает не то, что у нее написано в документации

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
>          try:
зачем здесь `try-except`?

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
>      usr = User.get_or_create(User_id=message.chat.id)
использовать `user, _  = ...`

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
>              bot.send_message(usr[0].User_id, 'Извините, в данный момент я не могу этого сделать.')
где-то отправляешь сообщения по `user.user_id`, где-то по `message.chat.id`

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +            bot.send_message(message.chat.id, text,parse_mode='Markdown')
обрати внимание - все до единого `bot.send_message` и прочие используют `user.user_id`
есть настойчивое предложение вынести эти функции в модель:
```python
bot = telebot.Bot(...)
class User(Model):
    def send_message(self, text, parse_mode='Markdown', keyboard=None, ..):
        bot.send_message(self.user_id, text, parse_mode, keyboard...)
```
тогда отправка сообщений будет выглядеть следующим образом:
```python
user, _ = User.get_or_create(...)
....
user.send_message(text)
```

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
>      User_id = CharField(unique=True)
telegram_id

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
>  def repeat_all_messages(message):
повторять все сообщения?)

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +            if len(choice) == 1:
просто else

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +                for temp in choice:
temp?

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +    choice = []
choices

2016-10-29 14:37 UTC, b0g3r commented on query_bot.py
> +                try:
чтобы избавиться от try/catch - возвращай из search ещё тип

2016-10-31 20:30 UTC, orangeatom commented on query_bot.py
> +            print(teacher.teacher_name)
это для тестов, проверял робит не робит.

2016-12-23 18:47 UTC, merged